import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Oslo Roller Derby</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    </div>
  );
}
