import Head from "next/head";
import styled from "styled-components";
//import Image from "next/image";

import Navigation from "../components/Navigation";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Oslo Roller Derby</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <HeaderBase>
        <Navigation />
        <img src="/images/HeroImage.png" />
      </HeaderBase>
      <main></main>
      <footer></footer>
    </div>
  );
}

const HeaderBase = styled.header`
  border: 1px solid black;
  height: 58rem;
  width: 100%;
  background-color: lightgrey;
  display: flex;
  flex-direction: column;
  justify-content: space-between;

  img {
    height: 415px;
    width: 70%;
    align-self: flex-end;
  }
`;
