import Head from "next/head";
//import Image from "next/image";

import Navigation from "../components/Navigation";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Oslo Roller Derby</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <header>
        <Navigation />
      </header>
    </div>
  );
}
